name: Daily News
 
on:
  schedule:
    - cron: '30 9 * * *'  # 06:30 Brasília time (UTC-3)
 
jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
 
      - run: npm install
 
      - run: node main.js
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
  